apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # The identifier of this Deployment, unique within a namespace.
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  name: {{ template "name" . }}
  # Labels are custom fields useful for querying and filtering resources.
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  # How many pods are running. Can be overriden by the HorizontalPodAutoscaler.
  replicas: {{ .Values.replicaCount }}
  # Determines the number of old ReplicaSets to be retained for this Deployment.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy
  revisionHistoryLimit: 2
  # Specifies a label selector for the Pods targeted by this Deployment.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector
  selector:
    matchLabels:
      app: {{ template "name" . }}
  # Specifies the strategy used to replace old Pods by new ones.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
{{ toYaml .Values.rollingUpdateStrategy | indent 6 }}
  # Specifies the minimum number of seconds for which a newly created Pod should
  # be ready without any of its containers crashing, for it to be considered available.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds
  minReadySeconds: 5
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /app/config.py
          name: config
          subPath: config.py
        - mountPath: /app/secrets.py
          name: config
          subPath: secrets.py
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
      resources:
{{ toYaml .Values.resources | indent 10 }}
