apiVersion: v1

image:
  repository: gcr.io/commercetools-platform/expert-bot
  tag: latest
  pullPolicy: Always

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment
rollingUpdateStrategy:
  maxSurge: 1
  maxUnavailable: 0

hpa:
  enabled: false

ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  annotations:
    kubernetes.io/ingress.allow-http: "false"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

config:
  REDIS_URL: redis://redis.external:6379
  HIPCHAT_ROOMS: '[]'
  HIPCHAT_DEFAULT_ROOM: ''

secrets:
  SECRET_KEY: ''
  HIPCHAT_PASSWORD: ''
  HIPCHAT_V2_TOKEN: ''
  HIPCHAT_USERNAME: ''

resources:
  limits:
    cpu: 1
    memory: "1.4Gi"
  requests:
    cpu: 1
    memory: "1.4Gi"

